
spring.mail.username=feljava32@gmail.com
spring.mail.password=hzub gfpg jbpd skoj

# Configuração do Remetente
envio.email.remetente=feljava32@gmail.com
envio.email.nomeRemetente=FCross

# RabbitMQ (Se estiver no Docker)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672