spring.application.name=notificacao
spring.jackson.time-zone=America/Sao_Paulo
spring.profiles.active=local
logging.file.name=logs/notificacao.log
logging.level.root=INFO
logging.level.com.projetozero=DEBUG