server:
  port: 8083

spring:
  application:
    name: notificacao
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: feljava32@gmail.com
    password: hzub gfpg jbpd skoj
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

thymeleaf:
  enabled: true

envio:
  email:
    remetente: feljava32@gmail.com
    nomeRemetente: 'FCross'