server:
  port: 8083

spring:
  application:
    name: notificacao

  # Agrupando tudo que é do Spring aqui
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  thymeleaf:
    enabled: true

envio:
  email:
    remetente: ${MAIL_USERNAME}
    nomeRemetente: 'FCross'